name: release check

on:
  push:
    branches:
      - "tagpr-from-*"

jobs:
  check:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm run test-manifest
